# Generated by Django 5.0.2 on 2025-05-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solicitante', models.CharField(max_length=100)),
                ('setor_solicitante', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('local_servico', models.CharField(max_length=100)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_servico', models.CharField(choices=[('Elétrico', 'Elétrico'), ('Hidráulico', 'Hidráulico'), ('Refrigeração', 'Refrigeração'), ('Pintura', 'Pintura'), ('Outro', 'Outro')], max_length=50)),
                ('outro_servico', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_manutencao', models.CharField(choices=[('Corretiva', 'Corretiva'), ('Preventiva', 'Preventiva'), ('Melhoria', 'Melhoria')], max_length=50)),
                ('descricao_problema', models.TextField()),
            ],
        ),
    ]
